name: EC_KDStats
main: br.com.explorecraft.ec_kdstats.EC_KDStats
version: 1.0
author: [TheExplorerBR]
commands:
  kdstats:
    description: "Look Kill/Death statistics of player"    
    usage: "/kdstats <player>" 